version: '3.9'

services:
  api:
    image: node
    container_name: cheer
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn && yarn dev"
    restart: always
    networks:
      - app
    depends_on:
      - redis
      - postgres
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    volumes:
      - ./db-data/redis/:/data
    restart: always
    networks:
      - app
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - app
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/templates/
    environment:
      - NGINX_HOST=api.localhost
      - NGINX_PORT=80
    extra_hosts:
      - api.localhost:127.0.0.1
      - client.localhost:127.0.0.1
    networks:
      - app
networks:
  app:
    driver: bridge
